import type { Profile } from "@shared/schema";

export const seedProfiles: Profile[] = [
  {
    id: "seed-maya",
    firstName: "Maya",
    age: 34,
    neighborhood: "Mission District, SF",
    values: ["Authenticity", "Growth", "Creativity"],
    fridayNight: "Cook dinner and deep conversation",
    lookingFor: "A serious relationship",
    communicationStyle: "Warm and nurturing",
    nonNegotiables: ["Emotional availability", "Intellectual connection"],
    unexpectedThing: "I fire my own ceramics in a backyard kiln I built from scratch",
    dietaryPreferences: ["Vegetarian"],
    readyToShowUp: true,
  },
  {
    id: "seed-james",
    firstName: "James",
    age: 38,
    neighborhood: "Hayes Valley, SF",
    values: ["Family", "Stability", "Humor"],
    fridayNight: "Game night with friends",
    lookingFor: "A life partner",
    communicationStyle: "Playful and witty",
    nonNegotiables: ["Same page on kids", "Sense of humor"],
    unexpectedThing: "I do competitive pub trivia and my team has won the city league twice",
    dietaryPreferences: ["No restrictions"],
    readyToShowUp: true,
  },
  {
    id: "seed-priya",
    firstName: "Priya",
    age: 31,
    neighborhood: "Downtown Oakland",
    values: ["Adventure", "Ambition", "Community"],
    fridayNight: "Live music or comedy show",
    lookingFor: "Exploring with intention",
    communicationStyle: "Direct and honest",
    nonNegotiables: ["Intellectual connection", "Aligned values"],
    unexpectedThing: "I left a law career to start a climate tech company and haven't looked back",
    dietaryPreferences: ["Vegan"],
    readyToShowUp: true,
  },
  {
    id: "seed-daniel",
    firstName: "Daniel",
    age: 36,
    neighborhood: "Noe Valley, SF",
    values: ["Kindness", "Growth", "Stability"],
    fridayNight: "Try a new restaurant",
    lookingFor: "A life partner",
    communicationStyle: "Thoughtful and reserved",
    nonNegotiables: ["Emotional availability", "Shared life goals"],
    unexpectedThing: "I spent a year living in a monastery in Japan learning woodworking",
    dietaryPreferences: ["No restrictions"],
    readyToShowUp: true,
  },
  {
    id: "seed-aisha",
    firstName: "Aisha",
    age: 33,
    neighborhood: "Temescal, Oakland",
    values: ["Spirituality", "Authenticity", "Community"],
    fridayNight: "Cozy night with a book",
    lookingFor: "A serious relationship",
    communicationStyle: "Warm and nurturing",
    nonNegotiables: ["Aligned values", "Emotional availability"],
    unexpectedThing: "I run a monthly storytelling night at a local bookshop that regularly sells out",
    dietaryPreferences: ["Halal"],
    readyToShowUp: true,
  },
  {
    id: "seed-marcus",
    firstName: "Marcus",
    age: 40,
    neighborhood: "Bernal Heights, SF",
    values: ["Humor", "Adventure", "Independence"],
    fridayNight: "Outdoor adventure",
    lookingFor: "Exploring with intention",
    communicationStyle: "Playful and witty",
    nonNegotiables: ["Physical chemistry", "Sense of humor"],
    unexpectedThing: "I once biked the entire Pacific Coast Highway solo and documented it as a photo essay",
    dietaryPreferences: ["Gluten-free"],
    readyToShowUp: true,
  },
  {
    id: "seed-elena",
    firstName: "Elena",
    age: 37,
    neighborhood: "North Beach, SF",
    values: ["Creativity", "Family", "Authenticity"],
    fridayNight: "Cook dinner and deep conversation",
    lookingFor: "A life partner",
    communicationStyle: "Direct and honest",
    nonNegotiables: ["Same page on kids", "Shared life goals"],
    unexpectedThing: "I restored a 1968 Fiat 500 by hand — it still runs and I drive it to the farmers market",
    dietaryPreferences: ["No restrictions"],
    readyToShowUp: true,
  },
  {
    id: "seed-kevin",
    firstName: "Kevin",
    age: 35,
    neighborhood: "SoMa, SF",
    values: ["Ambition", "Growth", "Humor"],
    fridayNight: "Try a new restaurant",
    lookingFor: "A serious relationship",
    communicationStyle: "Direct and honest",
    nonNegotiables: ["Intellectual connection", "Financial stability"],
    unexpectedThing: "I'm a software engineer by day but I've been secretly writing a graphic novel for three years",
    dietaryPreferences: ["No restrictions"],
    readyToShowUp: true,
  },
  {
    id: "seed-olivia",
    firstName: "Olivia",
    age: 32,
    neighborhood: "Cole Valley, SF",
    values: ["Adventure", "Kindness", "Creativity"],
    fridayNight: "Live music or comedy show",
    lookingFor: "A serious relationship",
    communicationStyle: "Playful and witty",
    nonNegotiables: ["Sense of humor", "Physical chemistry"],
    unexpectedThing: "I teach improv on weekends and once opened for a nationally touring comedian",
    dietaryPreferences: ["Vegetarian"],
    readyToShowUp: true,
  },
  {
    id: "seed-raj",
    firstName: "Raj",
    age: 41,
    neighborhood: "Rockridge, Oakland",
    values: ["Family", "Stability", "Spirituality"],
    fridayNight: "Cook dinner and deep conversation",
    lookingFor: "A life partner",
    communicationStyle: "Warm and nurturing",
    nonNegotiables: ["Same page on kids", "Aligned values"],
    unexpectedThing: "I coach little league baseball even though I don't have kids yet — it's my favorite thing",
    dietaryPreferences: ["Vegetarian"],
    readyToShowUp: true,
  },
  {
    id: "seed-sophia",
    firstName: "Sophia",
    age: 30,
    neighborhood: "Pacific Heights, SF",
    values: ["Independence", "Ambition", "Growth"],
    fridayNight: "Outdoor adventure",
    lookingFor: "Exploring with intention",
    communicationStyle: "Thoughtful and reserved",
    nonNegotiables: ["Intellectual connection", "Financial stability"],
    unexpectedThing: "I summited Kilimanjaro on my 30th birthday and journaled every step of the way",
    dietaryPreferences: ["Gluten-free"],
    readyToShowUp: true,
  },
  {
    id: "seed-chris",
    firstName: "Chris",
    age: 44,
    neighborhood: "Inner Sunset, SF",
    values: ["Community", "Kindness", "Humor"],
    fridayNight: "Game night with friends",
    lookingFor: "Building my community first",
    communicationStyle: "Warm and nurturing",
    nonNegotiables: ["Emotional availability", "Sense of humor"],
    unexpectedThing: "I foster rescue dogs — I've placed 23 so far and only 'failed' twice by keeping them",
    dietaryPreferences: ["No restrictions"],
    readyToShowUp: true,
  },
];
