import type { Profile } from "@shared/schema";

export const seedProfiles: Profile[] = [
  {
    id: "seed-maya",
    firstName: "Maya",
    age: 34,
    neighborhood: "Mission District, SF",
    genderIdentity: "Woman",
    genderSelfDescribe: "",
    pronouns: "She/her",
    pronounsOther: "",
    interestedIn: ["Men", "Nonbinary folks"],
    values: ["Authenticity", "Growth", "Creativity"],
    fridayNight: "Cook dinner and deep conversation",
    relationshipVision: "A partnership built on mutual curiosity where we challenge each other to grow",
    pastLesson: "I learned that love isn't about fixing someone — it's about accepting them while they do their own work",
    loveLanguage: "Quality Time",
    conflictStyle: "Need space first then talk",
    lookingFor: "A serious relationship",
    communicationStyle: "Warm and nurturing",
    nonNegotiables: ["Emotional availability", "Intellectual connection"],
    unexpectedThing: "I fire my own ceramics in a backyard kiln I built from scratch",
    dietaryPreferences: ["Vegetarian"],
    readyToShowUp: true,
  },
  {
    id: "seed-james",
    firstName: "James",
    age: 38,
    neighborhood: "Hayes Valley, SF",
    genderIdentity: "Man",
    genderSelfDescribe: "",
    pronouns: "He/him",
    pronounsOther: "",
    interestedIn: ["Women"],
    values: ["Family", "Stability", "Humor"],
    fridayNight: "Game night with friends",
    relationshipVision: "Building a home together that's full of laughter, kids, and Sunday morning pancakes",
    pastLesson: "I realized I was so focused on being the 'fun one' that I wasn't showing my deeper side",
    loveLanguage: "Acts of Service",
    conflictStyle: "Use humor to defuse",
    lookingFor: "A life partner",
    communicationStyle: "Playful and witty",
    nonNegotiables: ["Same page on kids", "Sense of humor"],
    unexpectedThing: "I do competitive pub trivia and my team has won the city league twice",
    dietaryPreferences: ["No restrictions"],
    readyToShowUp: true,
  },
  {
    id: "seed-priya",
    firstName: "Priya",
    age: 31,
    neighborhood: "Downtown Oakland",
    genderIdentity: "Woman",
    genderSelfDescribe: "",
    pronouns: "She/her",
    pronounsOther: "",
    interestedIn: ["Women", "Nonbinary folks"],
    values: ["Adventure", "Ambition", "Community"],
    fridayNight: "Live music or comedy show",
    relationshipVision: "Two ambitious people who are each other's biggest cheerleaders and adventure partners",
    pastLesson: "I learned that being vulnerable isn't weakness — it's the bravest thing you can do in a relationship",
    loveLanguage: "Words of Affirmation",
    conflictStyle: "Talk it through immediately",
    lookingFor: "Exploring with intention",
    communicationStyle: "Direct and honest",
    nonNegotiables: ["Intellectual connection", "Aligned values"],
    unexpectedThing: "I left a law career to start a climate tech company and haven't looked back",
    dietaryPreferences: ["Vegan"],
    readyToShowUp: true,
  },
  {
    id: "seed-daniel",
    firstName: "Daniel",
    age: 36,
    neighborhood: "Noe Valley, SF",
    genderIdentity: "Man",
    genderSelfDescribe: "",
    pronouns: "He/him",
    pronounsOther: "",
    interestedIn: ["Men"],
    values: ["Kindness", "Growth", "Stability"],
    fridayNight: "Try a new restaurant",
    relationshipVision: "A quiet, steady love where we can be fully ourselves without performing",
    pastLesson: "I learned that compatibility isn't about having the same interests — it's about having the same depth",
    loveLanguage: "Physical Touch",
    conflictStyle: "Need space first then talk",
    lookingFor: "A life partner",
    communicationStyle: "Thoughtful and reserved",
    nonNegotiables: ["Emotional availability", "Shared life goals"],
    unexpectedThing: "I spent a year living in a monastery in Japan learning woodworking",
    dietaryPreferences: ["No restrictions"],
    readyToShowUp: true,
  },
  {
    id: "seed-aisha",
    firstName: "Aisha",
    age: 33,
    neighborhood: "Temescal, Oakland",
    genderIdentity: "Woman",
    genderSelfDescribe: "",
    pronouns: "She/her",
    pronounsOther: "",
    interestedIn: ["Men"],
    values: ["Spirituality", "Authenticity", "Community"],
    fridayNight: "Cozy night with a book",
    relationshipVision: "A spiritually grounded partnership where we lift each other closer to our best selves",
    pastLesson: "I learned that I need someone who communicates openly, even when it's uncomfortable",
    loveLanguage: "Words of Affirmation",
    conflictStyle: "Write my feelings down",
    lookingFor: "A serious relationship",
    communicationStyle: "Warm and nurturing",
    nonNegotiables: ["Aligned values", "Emotional availability"],
    unexpectedThing: "I run a monthly storytelling night at a local bookshop that regularly sells out",
    dietaryPreferences: ["Halal"],
    readyToShowUp: true,
  },
  {
    id: "seed-marcus",
    firstName: "Marcus",
    age: 40,
    neighborhood: "Bernal Heights, SF",
    genderIdentity: "Man",
    genderSelfDescribe: "",
    pronouns: "He/him",
    pronounsOther: "",
    interestedIn: ["Women", "Men", "All genders"],
    values: ["Humor", "Adventure", "Independence"],
    fridayNight: "Outdoor adventure",
    relationshipVision: "A partnership where we have our own worlds but choose to orbit each other",
    pastLesson: "I learned that I was guarding my independence so hard I wasn't letting anyone in",
    loveLanguage: "Quality Time",
    conflictStyle: "Use humor to defuse",
    lookingFor: "Exploring with intention",
    communicationStyle: "Playful and witty",
    nonNegotiables: ["Physical chemistry", "Sense of humor"],
    unexpectedThing: "I once biked the entire Pacific Coast Highway solo and documented it as a photo essay",
    dietaryPreferences: ["Gluten-free"],
    readyToShowUp: true,
  },
  {
    id: "seed-elena",
    firstName: "Elena",
    age: 37,
    neighborhood: "North Beach, SF",
    genderIdentity: "Woman",
    genderSelfDescribe: "",
    pronouns: "She/her",
    pronounsOther: "",
    interestedIn: ["Men"],
    values: ["Creativity", "Family", "Authenticity"],
    fridayNight: "Cook dinner and deep conversation",
    relationshipVision: "A creative household where art, food, and family all blend together beautifully",
    pastLesson: "I learned that you can't build a future with someone who's still living in their past",
    loveLanguage: "Acts of Service",
    conflictStyle: "Talk it through immediately",
    lookingFor: "A life partner",
    communicationStyle: "Direct and honest",
    nonNegotiables: ["Same page on kids", "Shared life goals"],
    unexpectedThing: "I restored a 1968 Fiat 500 by hand — it still runs and I drive it to the farmers market",
    dietaryPreferences: ["No restrictions"],
    readyToShowUp: true,
  },
  {
    id: "seed-sam",
    firstName: "Sam",
    age: 35,
    neighborhood: "SoMa, SF",
    genderIdentity: "Nonbinary",
    genderSelfDescribe: "",
    pronouns: "They/them",
    pronounsOther: "",
    interestedIn: ["All genders"],
    values: ["Ambition", "Growth", "Humor"],
    fridayNight: "Try a new restaurant",
    relationshipVision: "A relationship where we co-create something beautiful and keep surprising each other",
    pastLesson: "I learned that being fully seen is scarier than being alone — but infinitely more rewarding",
    loveLanguage: "Receiving Gifts",
    conflictStyle: "Write my feelings down",
    lookingFor: "A serious relationship",
    communicationStyle: "Direct and honest",
    nonNegotiables: ["Intellectual connection", "Financial stability"],
    unexpectedThing: "I'm a software engineer by day but I've been secretly writing a graphic novel for three years",
    dietaryPreferences: ["No restrictions"],
    readyToShowUp: true,
  },
  {
    id: "seed-olivia",
    firstName: "Olivia",
    age: 32,
    neighborhood: "Cole Valley, SF",
    genderIdentity: "Woman",
    genderSelfDescribe: "",
    pronouns: "She/her",
    pronounsOther: "",
    interestedIn: ["Women", "Nonbinary folks"],
    values: ["Adventure", "Kindness", "Creativity"],
    fridayNight: "Live music or comedy show",
    relationshipVision: "Someone who makes ordinary moments feel extraordinary — laughter over everything",
    pastLesson: "I learned that chemistry without emotional safety is just anxiety with a nice face",
    loveLanguage: "Physical Touch",
    conflictStyle: "Talk it through immediately",
    lookingFor: "A serious relationship",
    communicationStyle: "Playful and witty",
    nonNegotiables: ["Sense of humor", "Physical chemistry"],
    unexpectedThing: "I teach improv on weekends and once opened for a nationally touring comedian",
    dietaryPreferences: ["Vegetarian"],
    readyToShowUp: true,
  },
  {
    id: "seed-raj",
    firstName: "Raj",
    age: 41,
    neighborhood: "Rockridge, Oakland",
    genderIdentity: "Man",
    genderSelfDescribe: "",
    pronouns: "He/him",
    pronounsOther: "",
    interestedIn: ["Women"],
    values: ["Family", "Stability", "Spirituality"],
    fridayNight: "Cook dinner and deep conversation",
    relationshipVision: "A warm, grounded partnership centered on family, faith, and shared traditions",
    pastLesson: "I learned that being patient doesn't mean settling — it means knowing what you deserve",
    loveLanguage: "Acts of Service",
    conflictStyle: "Need space first then talk",
    lookingFor: "A life partner",
    communicationStyle: "Warm and nurturing",
    nonNegotiables: ["Same page on kids", "Aligned values"],
    unexpectedThing: "I coach little league baseball even though I don't have kids yet — it's my favorite thing",
    dietaryPreferences: ["Vegetarian"],
    readyToShowUp: true,
  },
  {
    id: "seed-jordan",
    firstName: "Jordan",
    age: 30,
    neighborhood: "Pacific Heights, SF",
    genderIdentity: "Genderqueer",
    genderSelfDescribe: "",
    pronouns: "They/them",
    pronounsOther: "",
    interestedIn: ["Women", "Nonbinary folks", "All genders"],
    values: ["Independence", "Ambition", "Growth"],
    fridayNight: "Outdoor adventure",
    relationshipVision: "A partnership of equals who push each other toward their wildest dreams",
    pastLesson: "I learned that being independent doesn't mean doing everything alone",
    loveLanguage: "Quality Time",
    conflictStyle: "Need space first then talk",
    lookingFor: "Exploring with intention",
    communicationStyle: "Thoughtful and reserved",
    nonNegotiables: ["Intellectual connection", "Financial stability"],
    unexpectedThing: "I summited Kilimanjaro on my 30th birthday and journaled every step of the way",
    dietaryPreferences: ["Gluten-free"],
    readyToShowUp: true,
  },
  {
    id: "seed-chris",
    firstName: "Chris",
    age: 44,
    neighborhood: "Inner Sunset, SF",
    genderIdentity: "Man",
    genderSelfDescribe: "",
    pronouns: "He/him",
    pronounsOther: "",
    interestedIn: ["Men"],
    values: ["Community", "Kindness", "Humor"],
    fridayNight: "Game night with friends",
    relationshipVision: "A loving home full of dogs, dinner parties, and people who feel like family",
    pastLesson: "I learned that showing up consistently matters more than grand romantic gestures",
    loveLanguage: "Acts of Service",
    conflictStyle: "Talk it through immediately",
    lookingFor: "Building my community first",
    communicationStyle: "Warm and nurturing",
    nonNegotiables: ["Emotional availability", "Sense of humor"],
    unexpectedThing: "I foster rescue dogs — I've placed 23 so far and only 'failed' twice by keeping them",
    dietaryPreferences: ["No restrictions"],
    readyToShowUp: true,
  },
];
